build:
	sbt assembly
runServer:
	java -cp target/scala-3.1.0/todoList-assembly-0.1.0-SNAPSHOT.jar ru.neoflex.server.TodoServer
runClient:
	java -cp target/scala-3.1.0/todoList-assembly-0.1.0-SNAPSHOT.jar ru.neoflex.client.TodoClient